config/routes.rb
Rails.application.routes.draw do
  resources :dog_breeds, only: %i[index show], param: :breed
  root 'dog_breeds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dog_breeds_controller.rb
class DogBreedsController < ApplicationController

  def index
    @name = params[:breed]
    if @name.present?
      redirect_to dog_breed_path(@name)
    end
  end

  def show
    @name = params[:breed]
    @image_url = FetchDogBreed.new(@name).call
    if @image_url.nil?
      respond_to do |format|
        flash[:alert] = "Breed not found, please try again"
        format.html { redirect_to root_path }
      end
    else
      @image_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dog_breeds/index.html.erb
<h1>Find Dog Breed</h1>

<div id="flash-container">
  <%= render partial: 'shared/flash' %>
</div>

<%= turbo_frame_tag "form" do %>
  <%= render partial: 'shared/form' %>
<% end %>

app/views/dog_breeds/show.html.erb
<h1>Find Dog Breed</h1>

<%= turbo_frame_tag "form" do %>
  <%= render partial: 'shared/form' %>
<% end %>

<% if @image_url.present? %>
  <div class="mt-4">
		<h2><%= @name %></h2>
    <%= image_tag @image_url, class: "img-fluid", alt: "Breed Photo" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindDogBreed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/shared/_form.html.erb
<%= turbo_frame_tag 'form-frame' do %>
  <%= form_with(url: dog_breeds_path, method: 'get', class: "d-flex justify-content-between") do %>
    <div class="form-group">
      <%= label_tag :breed, "Breed:", class: "form-label" %>
      <%= text_field_tag :breed, nil, class: "form-control" %>
    </div>

    <%= submit_tag "Submit", class: "btn btn-primary" %>
  <% end %>
<% end %>